
# MovieLens-100K Dataset
movielens-100k-v1-interactions : https://github.com/recohut/reco-data/raw/master/movielens/100k/v1/interactions.zip
movielens-100k-v1-users : https://github.com/recohut/reco-data/raw/master/movielens/100k/v1/users.zip
movielens-100k-v1-items : https://github.com/recohut/reco-data/raw/master/movielens/100k/v1/items.zip

# BookCrossing Dataset
bookcrossing-v1-interactions : https://github.com/recohut/reco-data/raw/master/bookcrossing/v1/interactions.zip
bookcrossing-v1-users : https://github.com/recohut/reco-data/raw/master/bookcrossing/v1/users.zip
bookcrossing-v1-items : https://github.com/recohut/reco-data/raw/master/bookcrossing/v1/items.zip