
# MovieLens Dataset
movielens:
  100k:
    v1:
      interactions : https://github.com/recohut/reco-data/raw/master/movielens/100k/v1/interactions.zip
      users : https://github.com/recohut/reco-data/raw/master/movielens/100k/v1/users.zip
      items : https://github.com/recohut/reco-data/raw/master/movielens/100k/v1/items.zip

# BookCrossing Dataset
bookcrossing:
  v1:
    interactions: https://github.com/recohut/reco-data/raw/master/bookcrossing/v1/interactions.zip
    users : https://github.com/recohut/reco-data/raw/master/bookcrossing/v1/users.zip
    items : https://github.com/recohut/reco-data/raw/master/bookcrossing/v1/items.zip

# IJCAI 2016 Tmall Dataset
tmall:
  v1:
    interactions: https://disk.yandex.ru/d/YouI7jkZe4Bh-w
    train: https://github.com/recohut/reco-data/raw/master/tmall/v1/train.zip
    test: https://github.com/recohut/reco-data/raw/master/tmall/v1/test.zip
    merchants: https://github.com/recohut/reco-data/raw/master/tmall/v1/merchant.zip

# YooChoose RecSys'15 Dataset
yoochoose:
  v1:
    clicks: https://disk.yandex.ru/d/o9qvLeoDQGRa9Q
    buys: https://github.com/recohut/reco-data/raw/master/yoochoose/v1/buys.zip

# Trivago RecSys'19 Challenge dataset
trivago:
  v1:
    train: https://disk.yandex.ru/d/fFEvSaj6Cdplug
    test: https://disk.yandex.ru/d/_kAw9ajZuIC3rg
    items: https://github.com/recohut/reco-data/raw/master/trivago/v1/item_metadata.parquet.gz
    confirmation: https://github.com/recohut/reco-data/raw/master/trivago/v1/confirmation.parquet.gz
    validation: https://github.com/recohut/reco-data/raw/master/trivago/v1/validation.parquet.gz

# E-commerce Cosmetics Store dataset of user behaviors, 5 months, also available on kaggle
cosmetics:
  v1:
    chunk1: https://disk.yandex.ru/d/3YWOSn-fNubc2g
    chunk2: https://disk.yandex.ru/d/-sr3HBJEEeZNbg
    chunk3: https://disk.yandex.ru/d/gVtlTL2Xs_k4Aw
    chunk4: https://disk.yandex.ru/d/F2xsceqoXyG4hg
    chunk5: https://disk.yandex.ru/d/Cu8IPFiPiVnDOQ

# User-article edit history interactions, check out https://github.com/drsaunders/wikirecs
wikirecs:
  v1:
    interactions: https://disk.yandex.ru/d/j6SR4E7A2mbMOw

# SIGIR'21 E-commerce Challenge, sponsored by coveo, check out https://github.com/drsaunders/wikirecs
coveo:
  v1:
    browsing: https://disk.yandex.ru/d/UNZxwA_y2McPuQ
    searching: https://disk.yandex.ru/d/87aYRS-dx1rNqQ
    metadata: https://disk.yandex.ru/d/Jv3wzxEORTuIXg
    labels: https://disk.yandex.ru/d/S4JTnm_AwjVg8w
